version: '3.8'
services:
  hackathon:
    container_name: hackathon
    image: "hackathon:${BUILD_VERSION}"
    hostname: hackathon
    restart: always
    volumes:
      - .:/hackathon
    environment:
      - DGRAPH_ADDRESS=${DGRAPH_ADDRESS}
      - DGRAPH_PORT=${DGRAPH_PORT}
      - SERVER_ENV=${SERVER_ENV}
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - "8002:8002"
    networks:
      - hackathon

  dgraph-hackathon:
    image: dgraph/standalone:v21.03.0
    container_name: dgraph-hackathon
    ports:
      - "6081:6080"
      - "8001:8000"
      - "8081:8080"
      - "9081:9080"
    restart: always
    networks:
      - hackathon

networks:
  hackathon:
    name: hackathon
