version: '3.8'
services:
  hackathon:
    container_name: hackathon
    image: "hackathon:${BUILD_VERSION}"
    hostname: hackathon
    restart: always
    volumes:
      - .:/hackathon
    environment:
      - DGRAPH_ADDRESS=${DGRAPH_ADDRESS}
      - DGRAPH_PORT=${DGRAPH_PORT}
      - SERVER_ENV=${SERVER_ENV}
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - "8002:8002"
